
import { Project, Event, Testimonial, NavLink } from './types';

export const navLinks: NavLink[] = [
    { name: 'Services', path: '/services' },
    { name: 'Portfolio', path: '/portfolio' },
    { name: 'FANN Studio', path: '/fann-studio' },
    { 
        name: 'Resources', 
        children: [
            { name: 'Cost Calculator', path: '/resources/cost-calculator' },
            { name: 'Exhibition Guide', path: '/resources/exhibition-guide' },
            { name: '2026 Trends Report', path: '/resources/trends-2026' },
            { name: 'Events Calendar', path: '/events-calendar' },
            { name: 'ROI Calculator', path: '/roi-calculator' },
            { name: 'Intelligence Hub', path: '/insights' },
        ] 
    },
    { 
        name: 'About Us', 
        children: [
            { name: 'About FANN', path: '/about' },
            { name: 'Contact Us', path: '/contact' },
        ] 
    },
];

export const supportedLanguages = [
  { code: 'en', name: 'English' },
  { code: 'ar', name: 'Arabic' },
  { code: 'zh-CN', name: 'Chinese (Simp.)' },
  { code: 'hi', name: 'Hindi' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'ru', name: 'Russian' },
  { code: 'de', name: 'German' },
  { code: 'ja', name: 'Japanese' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'tr', name: 'Turkish' },
];

export const projects: Project[] = [
  
  // =============================================
  // EXHIBITION PROJECTS (1-20)
  // =============================================
  
  // --- GITEX (Technology) ---
  {
    id: 1,
    title: "GITEX Global 2024 - Enterprise AI",
    client: "Deloitte Middle East",
    category: "exhibition",
    size: "120 sqm",
    configuration: "Island",
    location: "Dubai World Trade Centre",
    industry: "Technology",
    year: 2024,
    description: "Premium double-decker stand showcasing AI consulting services and blockchain solutions with interactive demos and VIP meeting rooms.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80",
    tags: ["Technology", "Large Scale", "GITEX", "Premium"],
    featured: true
  },
  {
    id: 2,
    title: "GITEX 2023 - Cloud Infrastructure",
    client: "Microsoft Azure",
    category: "exhibition",
    size: "95 sqm",
    configuration: "Peninsula",
    location: "Dubai World Trade Centre",
    industry: "Technology",
    year: 2023,
    description: "Modern stand featuring cloud computing demos, developer workshops, and Azure AI showcase. Blue and white branding with interactive touchscreens.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80",
    tags: ["Technology", "Cloud", "GITEX"],
    featured: false
  },
  {
    id: 3,
    title: "GITEX 2022 - 5G Solutions",
    client: "Ericsson Middle East",
    category: "exhibition",
    size: "18 sqm",
    configuration: "Inline",
    location: "Dubai World Trade Centre",
    industry: "Telecommunications",
    year: 2022,
    description: "Compact stand demonstrating 5G technology with live network demos and IoT applications. Efficient use of small space with eye-catching LED displays.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80",
    tags: ["Technology", "Telecom", "GITEX", "Small"],
    featured: false
  },

  // --- Arab Health (Healthcare) ---
  {
    id: 4,
    title: "Arab Health 2024 - Medical Imaging",
    client: "Siemens Healthineers",
    category: "exhibition",
    size: "96 sqm",
    configuration: "Island",
    location: "Dubai World Trade Centre",
    industry: "Healthcare",
    year: 2024,
    description: "Sophisticated stand displaying advanced MRI and CT equipment with clinical consultation zones and technical demonstration areas.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80",
    tags: ["Healthcare", "Arab Health", "Medical Equipment"],
    featured: true
  },
  {
    id: 5,
    title: "Arab Health 2023 - Pharmaceutical Solutions",
    client: "Julphar Pharmaceuticals",
    category: "exhibition",
    size: "32 sqm",
    configuration: "Corner",
    location: "Dubai World Trade Centre",
    industry: "Pharmaceuticals",
    year: 2023,
    description: "Professional pharma stand with product displays, consultation area, and educational materials. Clean white and blue healthcare aesthetic.",
    image: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=1200&q=80",
    tags: ["Healthcare", "Pharma", "Arab Health", "Small"],
    featured: false
  },
  {
    id: 6,
    title: "Arab Health 2022 - Healthcare IT",
    client: "Cerner Middle East",
    category: "exhibition",
    size: "24 sqm",
    configuration: "Inline",
    location: "Dubai World Trade Centre",
    industry: "Healthcare Technology",
    year: 2022,
    description: "Compact tech-focused stand showcasing electronic health records and digital health solutions with demo stations.",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=1200&q=80",
    tags: ["Healthcare", "Technology", "Arab Health", "Small"],
    featured: false
  },

  // --- Gulfood (Food & Beverage) ---
  {
    id: 7,
    title: "Gulfood 2024 - Dairy Products",
    client: "Lactalis Group",
    category: "exhibition",
    size: "64 sqm",
    configuration: "Peninsula",
    location: "Dubai World Trade Centre",
    industry: "Food & Beverage",
    year: 2024,
    description: "Elegant stand with refrigerated displays, tasting bar, and product showcase. Warm wood finishes with premium branding.",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&q=80",
    tags: ["Food & Beverage", "Gulfood", "Premium"],
    featured: true
  },
  {
    id: 8,
    title: "Gulfood 2023 - UAE Food Brands",
    client: "Agthia Group",
    category: "exhibition",
    size: "48 sqm",
    configuration: "Corner",
    location: "Dubai World Trade Centre",
    industry: "Food & Beverage",
    year: 2023,
    description: "Modern stand showcasing Al Ain water, juice, and dairy products with interactive sampling stations and sustainability messaging.",
    image: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=1200&q=80",
    tags: ["Food & Beverage", "Gulfood", "UAE Brands"],
    featured: false
  },
  {
    id: 9,
    title: "Gulfood 2022 - Coffee & Beverages",
    client: "Monin Middle East",
    category: "exhibition",
    size: "20 sqm",
    configuration: "Inline",
    location: "Dubai World Trade Centre",
    industry: "Beverages",
    year: 2022,
    description: "Compact cafe-style stand with live barista demos, product tasting, and vibrant branding. Efficient small-space design.",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
    tags: ["Food & Beverage", "Gulfood", "Small", "Beverages"],
    featured: false
  },

  // --- The Big 5 (Construction) ---
  {
    id: 10,
    title: "The Big 5 Dubai 2024",
    client: "Schneider Electric",
    category: "exhibition",
    size: "72 sqm",
    configuration: "Peninsula",
    location: "Dubai World Trade Centre",
    industry: "Construction Technology",
    year: 2024,
    description: "Technical stand featuring smart building solutions, electrical systems, and energy management with live automation demos.",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80",
    tags: ["Construction", "Technology", "Big 5"],
    featured: false
  },
  {
    id: 11,
    title: "The Big 5 2023 - Building Materials",
    client: "Al Ghurair Iron & Steel",
    category: "exhibition",
    size: "56 sqm",
    configuration: "Corner",
    location: "Dubai World Trade Centre",
    industry: "Construction Materials",
    year: 2023,
    description: "Industrial stand displaying steel products, technical specifications, and construction applications with material samples.",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200&q=80",
    tags: ["Construction", "Materials", "Big 5"],
    featured: false
  },
  {
    id: 12,
    title: "The Big 5 2022 - Smart Lighting",
    client: "Philips Lighting Middle East",
    category: "exhibition",
    size: "28 sqm",
    configuration: "Inline",
    location: "Dubai World Trade Centre",
    industry: "Construction",
    year: 2022,
    description: "Small but impactful stand showcasing architectural LED lighting solutions with working demos and design consultation area.",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=1200&q=80",
    tags: ["Construction", "Lighting", "Big 5", "Small"],
    featured: false
  },

  // --- Automechanika (Automotive) ---
  {
    id: 13,
    title: "Automechanika Dubai 2024",
    client: "Bosch Automotive",
    category: "exhibition",
    size: "84 sqm",
    configuration: "Island",
    location: "Dubai World Trade Centre",
    industry: "Automotive",
    year: 2024,
    description: "Professional automotive stand with parts display, diagnostic equipment demos, and technical workshop area. Red and black branding.",
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=1200&q=80",
    tags: ["Automotive", "Parts", "Automechanika"],
    featured: false
  },
  {
    id: 14,
    title: "Automechanika 2023 - Tires",
    client: "Bridgestone Middle East",
    category: "exhibition",
    size: "36 sqm",
    configuration: "Corner",
    location: "Dubai World Trade Centre",
    industry: "Automotive",
    year: 2023,
    description: "Tire showcase stand with product displays, technical information, and consultation zone. Bold branding with product wall.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80",
    tags: ["Automotive", "Tires", "Automechanika"],
    featured: false
  },

  // --- Beautyworld (Beauty & Cosmetics) ---
  {
    id: 15,
    title: "Beautyworld Middle East 2024",
    client: "L'Oréal Middle East",
    category: "exhibition",
    size: "68 sqm",
    configuration: "Peninsula",
    location: "Dubai World Trade Centre",
    industry: "Beauty & Cosmetics",
    year: 2024,
    description: "Elegant beauty stand with product displays, makeup stations, hair styling area, and brand storytelling zones. Premium finishes throughout.",
    image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=1200&q=80",
    tags: ["Beauty", "Cosmetics", "Beautyworld", "Premium"],
    featured: false
  },
  {
    id: 16,
    title: "Beautyworld 2023 - Hair Care",
    client: "GHD Middle East",
    category: "exhibition",
    size: "24 sqm",
    configuration: "Inline",
    location: "Dubai World Trade Centre",
    industry: "Beauty",
    year: 2023,
    description: "Compact salon-style stand with live styling demos, product displays, and consultation area. Modern black and gold aesthetic.",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80",
    tags: ["Beauty", "Hair Care", "Beautyworld", "Small"],
    featured: false
  },

  // --- ADIPEC (Energy) ---
  {
    id: 17,
    title: "ADIPEC 2024 - Energy Solutions",
    client: "Shell Middle East",
    category: "exhibition",
    size: "200 sqm",
    configuration: "Island",
    location: "ADNEC Abu Dhabi",
    industry: "Energy",
    year: 2024,
    description: "Massive corporate stand showcasing LNG technology, renewable energy projects, and digital solutions with theater, lounge, and meeting rooms.",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&q=80",
    tags: ["Energy", "ADIPEC", "Large Scale", "Premium"],
    featured: true
  },
  {
    id: 18,
    title: "ADIPEC 2023 - Oilfield Services",
    client: "Schlumberger Middle East",
    category: "exhibition",
    size: "88 sqm",
    configuration: "Peninsula",
    location: "ADNEC Abu Dhabi",
    industry: "Energy",
    year: 2023,
    description: "Technical stand featuring drilling technology, digital oilfield solutions, and consultation areas. Professional industrial aesthetic.",
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=1200&q=80",
    tags: ["Energy", "ADIPEC", "Industrial"],
    featured: false
  },

  // --- Cityscape (Real Estate) ---
  {
    id: 19,
    title: "Cityscape Global 2024",
    client: "Emaar Properties",
    category: "exhibition",
    size: "120 sqm",
    configuration: "Island",
    location: "Dubai World Trade Centre",
    industry: "Real Estate",
    year: 2024,
    description: "Prestigious stand showcasing luxury developments with large-format visuals, VR property tours, and VIP consultation lounges.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    tags: ["Real Estate", "Luxury", "Cityscape", "Large Scale"],
    featured: true
  },
  {
    id: 20,
    title: "Cityscape 2023 - Developer Showcase",
    client: "Damac Properties",
    category: "exhibition",
    size: "64 sqm",
    configuration: "Peninsula",
    location: "Dubai World Trade Centre",
    industry: "Real Estate",
    year: 2023,
    description: "Elegant property showcase with project displays, payment plan information, and sales consultation areas.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80",
    tags: ["Real Estate", "Cityscape"],
    featured: false
  },

  // =============================================
  // EVENTS PROJECTS (21-28)
  // =============================================

  {
    id: 21,
    title: "Emirates NBD GenAI Summit 2025",
    client: "Emirates NBD Bank",
    category: "event",
    capacity: "350 attendees",
    location: "Ritz Carlton DIFC, Dubai",
    industry: "Banking",
    eventType: "Corporate Summit",
    year: 2025,
    description: "Premium technology conference bringing together global AI experts. Featured main stage, breakout sessions, exhibition area, and networking lounge.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80",
    tags: ["Corporate", "Technology", "Summit", "Banking"],
    featured: true
  },
  {
    id: 22,
    title: "HSBC MENAT Future Forum 2025",
    client: "HSBC Bank Middle East",
    category: "event",
    capacity: "800 attendees",
    location: "Atlantis The Palm, Dubai",
    industry: "Finance",
    eventType: "Financial Conference",
    year: 2025,
    description: "Three-day financial markets forum for institutional investors and regulators. Multiple conference halls, VIP networking areas, and gala dinner setup.",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&q=80",
    tags: ["Finance", "Conference", "Luxury", "Corporate"],
    featured: true
  },
  {
    id: 23,
    title: "Luxury Brand Launch - Swiss Watches",
    client: "Rolex Middle East",
    category: "event",
    capacity: "120 VIP guests",
    location: "Dubai Mall Fountain Plaza",
    industry: "Luxury",
    eventType: "Product Launch",
    year: 2024,
    description: "Exclusive evening event for new watch collection launch. Elegant setup with display cases, ambient lighting, and fountain view backdrop.",
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1200&q=80",
    tags: ["Luxury", "Product Launch", "VIP", "Retail"],
    featured: true
  },
  {
    id: 24,
    title: "Step Conference 2024",
    client: "Step Group",
    category: "event",
    capacity: "8,000 attendees",
    location: "Dubai World Trade Centre",
    industry: "Technology",
    eventType: "Tech Conference",
    year: 2024,
    description: "Major startup and tech conference with 6 specialized tracks. Multiple stages, exhibition area, investor lounge, and networking zones.",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&q=80",
    tags: ["Startups", "Technology", "Conference", "Large Scale"],
    featured: false
  },
  {
    id: 25,
    title: "Emirates NBD Annual Gala Dinner",
    client: "Emirates NBD Bank",
    category: "event",
    capacity: "500 guests",
    location: "Burj Al Arab, Dubai",
    industry: "Banking",
    eventType: "Corporate Gala",
    year: 2024,
    description: "Elegant annual appreciation gala with premium table settings, stage entertainment, award ceremony setup, and sophisticated lighting design.",
    image: "https://images.unsplash.com/photo-1519167758481-83f29da8c8d6?w=1200&q=80",
    tags: ["Gala", "Corporate", "Luxury", "Banking"],
    featured: false
  },
  {
    id: 26,
    title: "Arabian Luxury Dubai 2024",
    client: "Various Luxury Brands",
    category: "event",
    capacity: "300 VIP attendees",
    location: "Atlantis The Royal",
    industry: "Luxury",
    eventType: "Luxury Showcase",
    year: 2024,
    description: "Invitation-only luxury event featuring private properties, yachts, and premium experiences. Elegant display areas and VIP lounges.",
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1200&q=80",
    tags: ["Luxury", "VIP", "Networking", "Premium"],
    featured: true
  },
  {
    id: 27,
    title: "Dubai FinTech Summit 2024",
    client: "Dubai Economy",
    category: "event",
    capacity: "2,000 attendees",
    location: "Dubai World Trade Centre",
    industry: "Fintech",
    eventType: "Industry Summit",
    year: 2024,
    description: "Major fintech conference aligned with Dubai D33 Economic Agenda. Exhibition stands, innovation showcase, main stage, and startup pitch area.",
    image: "https://images.unsplash.com/photo-1556155092-490a1ba16284?w=1200&q=80",
    tags: ["Fintech", "Technology", "Summit", "Banking"],
    featured: false
  },
  {
    id: 28,
    title: "Fashion Futures Dubai 2024",
    client: "Dubai Design District",
    category: "event",
    capacity: "600 attendees",
    location: "Dubai Design District",
    industry: "Fashion",
    eventType: "Fashion Conference",
    year: 2024,
    description: "Luxury fashion industry summit with runway shows, exhibition areas, panel discussion stages, and VIP networking lounges.",
    image: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=1200&q=80",
    tags: ["Fashion", "Luxury", "Conference", "Design"],
    featured: false
  },

  // =============================================
  // INTERIOR DESIGN PROJECTS (29-40)
  // =============================================

  {
    id: 29,
    title: "Emirates NBD Executive Office DIFC",
    client: "Emirates NBD Bank",
    category: "interior",
    size: "520 sqm",
    location: "Dubai International Financial Centre",
    industry: "Banking",
    spaceType: "Corporate Office",
    year: 2024,
    description: "Premium executive office suite with glass partitions, custom Italian furniture, meeting rooms, and sophisticated navy blue and gold finishes.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80",
    tags: ["Corporate", "Office", "Luxury", "Banking"],
    featured: true
  },
  {
    id: 30,
    title: "HSBC Private Banking Lounge",
    client: "HSBC Bank Middle East",
    category: "interior",
    size: "380 sqm",
    location: "Emirates Towers, Dubai",
    industry: "Banking",
    spaceType: "Banking Lounge",
    year: 2024,
    description: "Ultra-luxury private banking lounge with consultation rooms, waiting area, and premium coffee service. Contemporary British design.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    tags: ["Banking", "Luxury", "Lounge", "Corporate"],
    featured: true
  },
  {
    id: 31,
    title: "Deloitte Consulting Hub",
    client: "Deloitte Middle East",
    category: "interior",
    size: "680 sqm",
    location: "Business Bay, Dubai",
    industry: "Consulting",
    spaceType: "Corporate Office",
    year: 2024,
    description: "Modern open-plan office with collaboration zones, meeting pods, innovation lab, and client presentation center. Sustainable materials.",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80",
    tags: ["Corporate", "Office", "Consulting", "Modern"],
    featured: false
  },
  {
    id: 32,
    title: "Google Cloud Regional Office",
    client: "Google Cloud MENA",
    category: "interior",
    size: "450 sqm",
    location: "Dubai Internet City",
    industry: "Technology",
    spaceType: "Tech Office",
    year: 2024,
    description: "Vibrant tech office space with open workstations, creative meeting rooms, game area, and innovation showcase zone.",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&q=80",
    tags: ["Technology", "Office", "Creative", "Modern"],
    featured: true
  },
  {
    id: 33,
    title: "Rolex Boutique Dubai Mall",
    client: "Rolex Middle East",
    category: "interior",
    size: "180 sqm",
    location: "Dubai Mall",
    industry: "Retail",
    spaceType: "Luxury Retail",
    year: 2024,
    description: "Prestigious watch boutique with custom display cases, VIP consultation room, secure vault, and elegant seating areas.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80",
    tags: ["Retail", "Luxury", "Watches", "Premium"],
    featured: true
  },
  {
    id: 34,
    title: "Siemens Healthcare Clinic",
    client: "Siemens Healthineers",
    category: "interior",
    size: "420 sqm",
    location: "Dubai Healthcare City",
    industry: "Healthcare",
    spaceType: "Medical Facility",
    year: 2025,
    description: "State-of-the-art medical diagnostic center with imaging rooms, consultation areas, and reception. Clean clinical design.",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80",
    tags: ["Healthcare", "Medical", "Clinical", "Technology"],
    featured: false
  },
  {
    id: 35,
    title: "Tetra Pak Innovation Center",
    client: "Tetra Pak Middle East",
    category: "interior",
    size: "550 sqm",
    location: "Dubai Industrial Park",
    industry: "Food Tech",
    spaceType: "Innovation Lab",
    year: 2024,
    description: "Industrial-modern innovation center with product testing lab, demonstration kitchen, meeting rooms, and exhibition area.",
    image: "https://images.unsplash.com/photo-1497366412874-3415097a27e7?w=1200&q=80",
    tags: ["Industrial", "Innovation", "Food Tech", "Commercial"],
    featured: false
  },
  {
    id: 36,
    title: "La Petite Maison Restaurant",
    client: "DIFC Restaurants Group",
    category: "interior",
    size: "320 sqm",
    location: "Dubai International Financial Centre",
    industry: "Hospitality",
    spaceType: "Fine Dining",
    year: 2024,
    description: "Upscale French Mediterranean restaurant with open kitchen, wine cellar display, private dining room, and outdoor terrace.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80",
    tags: ["Restaurant", "Hospitality", "Luxury", "Fine Dining"],
    featured: true
  },
  {
    id: 37,
    title: "Fitness First Platinum Club",
    client: "Fitness First Middle East",
    category: "interior",
    size: "800 sqm",
    location: "Downtown Dubai",
    industry: "Fitness",
    spaceType: "Fitness Center",
    year: 2024,
    description: "Premium gym facility with cardio zone, free weights area, functional training space, studio rooms, spa, and juice bar.",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80",
    tags: ["Fitness", "Wellness", "Commercial", "Modern"],
    featured: false
  },
  {
    id: 38,
    title: "Address Hotels Executive Lounge",
    client: "Address Hotels + Resorts",
    category: "interior",
    size: "450 sqm",
    location: "Address Boulevard, Downtown Dubai",
    industry: "Hospitality",
    spaceType: "Hotel Lounge",
    year: 2024,
    description: "Sophisticated hotel executive lounge with reception, seating zones, business center, breakfast area, and bar.",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80",
    tags: ["Hotel", "Hospitality", "Luxury", "Lounge"],
    featured: false
  },
  {
    id: 39,
    title: "Private Villa Emirates Hills",
    client: "Private Client",
    category: "interior",
    size: "950 sqm",
    location: "Emirates Hills, Dubai",
    industry: "Residential",
    spaceType: "Luxury Residence",
    year: 2024,
    description: "Ultra-luxury villa interior featuring grand entrance, formal living, family lounge, dining room, chef's kitchen, and home theater.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
    tags: ["Residential", "Villa", "Ultra Luxury", "Custom"],
    featured: true
  },
  {
    id: 40,
    title: "WeWork Co-Working Space",
    client: "WeWork Dubai",
    category: "interior",
    size: "620 sqm",
    location: "Dubai Marina",
    industry: "Real Estate",
    spaceType: "Co-Working",
    year: 2024,
    description: "Flexible workspace with hot desks, private offices, meeting rooms, phone booths, lounge area, and pantry.",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&q=80",
    tags: ["Office", "Co-Working", "Modern", "Flexible"],
    featured: false
  }
];

export const regionalEvents: Event[] = [
  // --- UAE 2024 ---
  { name: "Sleep Expo Middle East", date: "Sep 10-12, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Retail" },
  { name: "Sign and Graphic Imaging Middle East", date: "Sep 24-26, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Marketing" },
  { name: "The Hotel Show Dubai", date: "Sep 24-26, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Hospitality" },
  { name: "Watch & Jewellery Show Sharjah", date: "Oct 2-6, 2024", venue: "Expo Centre Sharjah", country: "UAE", industry: "Luxury" },
  { name: "Expand North Star", date: "Oct 13-16, 2024", venue: "Dubai Harbour", country: "UAE", industry: "Technology" },
  { name: "GITEX Global", date: "Oct 14-18, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Technology" },
  { name: "Fintech Surge", date: "Oct 14-18, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Finance" },
  { name: "Marketing Mania", date: "Oct 14-18, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Marketing" },
  { name: "World Blockchain Summit", date: "Oct 22-23, 2024", venue: "Atlantis, The Palm", country: "UAE", industry: "Finance" },
  { name: "NAJAH Abu Dhabi", date: "Oct 27-29, 2024", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Education" },
  { name: "Beautyworld Middle East", date: "Oct 28-30, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Beauty" },
  { name: "Sharjah International Book Fair", date: "Nov 1-12, 2024", venue: "Expo Centre Sharjah", country: "UAE", industry: "Culture" },
  { name: "Gulfood Manufacturing", date: "Nov 5-7, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "Downtown Design", date: "Nov 6-9, 2024", venue: "Dubai Design District (d3)", country: "UAE", industry: "Art & Design" },
  { name: "ADIPEC", date: "Nov 11-14, 2024", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Energy" },
  { name: "Cityscape Global", date: "Nov 19-21, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Real Estate" },
  { name: "Big 5 Global", date: "Nov 26-29, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Construction" },
  { name: "FM Expo", date: "Nov 26-29, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Real Estate" },
  { name: "Middle East Film & Comic Con", date: "Dec 6-8, 2024", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Entertainment" },
  { name: "MEBAA Show", date: "Dec 10-12, 2024", venue: "DWC, Dubai Airshow Site", country: "UAE", industry: "Aviation"},
  { name: "ArabPlast", date: "Dec 13-15, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Manufacturing" },

  // --- KSA 2024 ---
  { name: "Global Tech Summit", date: "Sep 10-12, 2024", venue: "King Abdulaziz Conference Center, Riyadh", country: "KSA", industry: "Technology" },
  { name: "Hotel & Hospitality Expo Saudi Arabia", date: "Sep 10-12, 2024", venue: "Riyadh Front", country: "KSA", industry: "Hospitality" },
  { name: "INDEX Saudi", date: "Sep 10-12, 2024", venue: "Riyadh Front", country: "KSA", industry: "Interior Design" },
  { name: "Cityscape Global KSA", date: "Sep 10-13, 2024", venue: "Riyadh Exhibition and Convention Center", country: "KSA", industry: "Real Estate" },
  { name: "Saudi Food Expo", date: "Sep 17-19, 2024", venue: "Riyadh Front", country: "KSA", industry: "Food & Beverage" },
  { name: "Saudi Infrastructure Expo", date: "Sep 24-26, 2024", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Construction" },
  { name: "Riyadh International Book Fair", date: "Sep 26 - Oct 5, 2024", venue: "Riyadh Front", country: "KSA", industry: "Culture" },
  { name: "Saudi Agriculture", date: "Oct 21-24, 2024", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Food & Beverage" },
  { name: "Global Health Exhibition", date: "Oct 27-29, 2024", venue: "Riyadh Front", country: "KSA", industry: "Healthcare" },
  { name: "Saudi Build", date: "Nov 4-7, 2024", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Construction" },
  { name: "Misk Global Forum", date: "Nov 12-14, 2024", venue: "Riyadh", country: "KSA", industry: "Education" },
  { name: "Saudi Power", date: "Nov 25-27, 2024", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Energy" },
  { name: "Black Hat Middle East & Africa", date: "Nov 26-28, 2024", venue: "Riyadh Front", country: "KSA", industry: "Security" },
  { name: "Saudi International Motor Show", date: "Dec 5-8, 2024", venue: "Jeddah Superdome", country: "KSA", industry: "Automotive" },
  { name: "Jeddah International Trade Fair", date: "Dec 15-18, 2024", venue: "Jeddah Centre for Forums & Events", country: "KSA", industry: "Retail" },

  // --- UAE 2025 ---
  { name: "World Future Energy Summit", date: "Jan 13-15, 2025", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Energy" },
  { name: "Intersec", date: "Jan 14-16, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Security" },
  { name: "Light Middle East", date: "Jan 17-19, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Construction" },
  { name: "World of Coffee Dubai", date: "Jan 21-23, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "Arab Health", date: "Jan 27-30, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Healthcare" },
  { name: "AEEDC Dubai", date: "Feb 4-6, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Healthcare" },
  { name: "Breakbulk Middle East", date: "Feb 10-11, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Logistics" },
  { name: "STEP Conference", date: "Feb 11-12, 2025", venue: "Dubai Internet City", country: "UAE", industry: "Technology" },
  { name: "International Property Show", date: "Feb 12-14, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Real Estate" },
  { name: "IDEX & NAVDEX", date: "Feb 17-21, 2025", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Defence" },
  { name: "Gulfood", date: "Feb 17-21, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "Dubai Food Festival", date: "Feb 28 - Mar 15, 2025", venue: "City-wide, Dubai", country: "UAE", industry: "Food & Beverage"},
  { name: "Dubai Derma", date: "Mar 3-5, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Healthcare" },
  { name: "World Police Summit", date: "Mar 5-7, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Security" },
  { name: "Dubai International Boat Show", date: "Mar 5-9, 2025", venue: "Dubai Harbour", country: "UAE", industry: "Luxury" },
  { name: "Art Dubai", date: "Mar 12-15, 2025", venue: "Madinat Jumeirah", country: "UAE", industry: "Art & Design" },
  { name: "Dubai International Horse Fair", date: "Mar 21-23, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Equestrian" },
  { name: "Custom Show Emirates", date: "Mar 21-23, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Automotive" },
  { name: "GESS Dubai", date: "Mar 25-27, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Education" },
  { name: "World Art Dubai", date: "Apr 2-5, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Art & Design" },
  { name: "Middle East Energy", date: "Apr 15-17, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Energy" },
  { name: "Global Future Show", date: "Apr 16-17, 2025", venue: "Dubai Festival City", country: "UAE", industry: "Technology" },
  { name: "GISEC Global", date: "Apr 21-23, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Technology" },
  { name: "Middle East Rail", date: "Apr 22-23, 2025", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Logistics" },
  { name: "Arabian Travel Market", date: "Apr 28 - May 1, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Hospitality" },
  { name: "CABSAT", date: "May 13-15, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Media" },
  { name: "Paperworld Middle East", date: "May 19-21, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Retail"},
  { name: "Airport Show", date: "May 20-22, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Aviation" },
  { name: "Automechanika Dubai", date: "May 27-29, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Automotive" },
  { name: "INDEX Dubai", date: "Jun 3-5, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Interior Design" },
  { name: "Seamless Middle East", date: "Sep 9-10, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Retail" },
  { name: "Seatrade Maritime Middle East", date: "Sep 16-18, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Logistics"},
  { name: "WETEX and Dubai Solar Show", date: "Sep 23-25, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Energy" },
  { name: "GITEX Global 2025", date: "Oct 13-17, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Technology" },
  { name: "Dubai Muscle Show & Dubai Active", date: "Oct 24-26, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Fitness" },
  { name: "Beautyworld Middle East 2025", date: "Oct 27-29, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Beauty" },
  { name: "Gulfood Manufacturing 2025", date: "Nov 4-6, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "Dubai Airshow", date: "Nov 17-21, 2025", venue: "DWC, Dubai Airshow Site", country: "UAE", industry: "Aviation" },
  { name: "Cityscape Global 2025", date: "Nov 18-20, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Real Estate" },
  { name: "Big 5 Global 2025", date: "Nov 25-28, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Construction" },
  { name: "Dubai International Jewellery Show", date: "Dec 2-5, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Luxury" },

  // --- KSA 2025 ---
  { name: "Saudi Plastics & Petrochem", date: "Jan 13-16, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Manufacturing" },
  { name: "Saudi Print & Pack", date: "Jan 27-30, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Manufacturing" },
  { name: "World Defense Show", date: "Feb 8-12, 2025", venue: "Riyadh", country: "KSA", industry: "Defence" },
  { name: "LEAP", date: "Feb 10-13, 2025", venue: "Riyadh Exhibition and Convention Center", country: "KSA", industry: "Technology" },
  { name: "The Big 5 Saudi", date: "Feb 24-27, 2025", venue: "Riyadh Front", country: "KSA", industry: "Construction" },
  { name: "Saudi Entertainment and Amusement (SEA) Expo", date: "May 20-22, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Entertainment" },
  { name: "Saudi Light & Sound Expo", date: "May 20-22, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Entertainment" },
  { name: "Saudi Elenex", date: "May 26-28, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Energy" },
  { name: "Saudi Health", date: "Oct 19-21, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Healthcare" },
  { name: "Foodex Saudi", date: "Oct 26-29, 2025", venue: "Jeddah Centre for Forums & Events", country: "KSA", industry: "Food & Beverage" },
  { name: "InFlavour", date: "Nov 11-13, 2025", venue: "Riyadh Front", country: "KSA", industry: "Food & Beverage" },
  
  // --- UAE 2026 (Projected Dates) ---
  { name: "Intersec 2026", date: "Jan 13-15, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Security" },
  { name: "Arab Health 2026", date: "Jan 26-29, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Healthcare" },
  { name: "Gulfood 2026", date: "Feb 16-20, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "GITEX Global 2026", date: "Oct 12-16, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Technology" },
  { name: "Big 5 Global 2026", date: "Nov 24-27, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Construction" },
  
  // --- KSA 2026 (Projected Dates) ---
  { name: "LEAP 2026", date: "Feb 9-12, 2026 (TBC)", venue: "Riyadh Exhibition and Convention Center", country: "KSA", industry: "Technology" },
  { name: "The Big 5 Saudi 2026", date: "Feb 23-26, 2026 (TBC)", venue: "Riyadh Front", country: "KSA", industry: "Construction" },
];

export const testimonials: Testimonial[] = [
  { quote: "FANN didn't just build a stand; they created an experience. Their attention to detail and project management is unparalleled. Our leads increased by 40%!", client: "Aisha Al Futtaim", company: "TechVision Systems", projectType: "GITEX Exhibition" },
  { quote: "The team at FANN is a dream to work with. They took our vision for the annual gala and elevated it beyond our wildest expectations. Flawless execution from start to finish.", client: "Johnathan Lee", company: "Global Leaders Org", projectType: "Corporate Event" },
  { quote: "Transforming our new headquarters with FANN was the best decision we made. The design is not only beautiful but has tangibly improved our team's collaboration and morale.", client: "Fatima Al Mansouri", company: "Emirates Tech Solutions", projectType: "Interior Design" },
];
