import { Project, Event, Testimonial, NavLink } from './types';

export const navLinks: NavLink[] = [
    { name: 'Services', path: '/services' },
    { name: 'Portfolio', path: '/portfolio' },
    { name: 'FANN Studio', path: '/fann-studio' },
    { name: 'Calendar', path: '/events-calendar' },
    { name: 'Pricing', path: '/pricing' },
    { 
        name: 'About Us', 
        children: [
            { name: 'About FANN', path: '/about' },
            { name: 'Intelligence Hub', path: '/insights' },
            { name: 'Contact Us', path: '/contact' },
        ] 
    },
];

export const supportedLanguages = [
  { code: 'en', name: 'English' },
  { code: 'zh-CN', name: 'Chinese (Simplified)' },
  { code: 'hi', name: 'Hindi' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'ar', name: 'Arabic' },
  { code: 'bn', name: 'Bengali' },
  { code: 'ru', name: 'Russian' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ur', name: 'Urdu' },
  { code: 'id', name: 'Indonesian' },
  { code: 'de', name: 'German' },
  { code: 'ja', name: 'Japanese' },
  { code: 'mr', name: 'Marathi' },
  { code: 'te', name: 'Telugu' },
  { code: 'tr', name: 'Turkish' },
  { code: 'ko', name: 'Korean' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'ta', name: 'Tamil' },
  { code: 'it', name: 'Italian' },
];


export const portfolioProjects: Project[] = [
  { id: 1, title: "TechVision AI", client: "GITEX 2024", service: "Exhibitions", industry: "Technology", scale: "Standard", year: 2024, image: "https://images.pexels.com/photos/8566427/pexels-photo-8566427.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 250, location: "Dubai World Trade Centre", timeline: "Concept to Completion: 8 weeks", challenge: "Integrating interactive AI demos seamlessly into a luxury, minimalist aesthetic.", result: "Generated over 5,000 qualified leads, a 40% increase from the previous year." },
  { id: 2, title: "MediCorp International", client: "Arab Health 2024", service: "Exhibitions", industry: "Healthcare", scale: "Standard", year: 2024, image: "https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 180, location: "Dubai World Trade Centre", timeline: "Concept to Completion: 7 weeks", challenge: "Creating a sterile, high-tech environment that felt approachable and welcoming.", result: "Secured distribution deals in 5 new MENA markets." },
  { id: 3, title: "AeroDefense Systems", client: "Dubai Air Show 2023", service: "Exhibitions", industry: "Aviation", scale: "Large", year: 2023, image: "https://images.pexels.com/photos/8297478/pexels-photo-8297478.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 400, location: "DWC, Dubai Airshow Site", timeline: "Concept to Completion: 12 weeks", challenge: "Building a secure, double-deck structure to host high-level government delegations.", result: "Facilitated over $50M in preliminary agreements." },
  { id: 4, title: "Artisan Delights", client: "Gulfood 2024", service: "Exhibitions", industry: "Hospitality", scale: "Standard", year: 2024, image: "https://images.pexels.com/photos/6647037/pexels-photo-6647037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 120, location: "Dubai World Trade Centre", timeline: "Concept to Completion: 6 weeks", challenge: "Designing an open-concept stand with live cooking stations and high foot traffic.", result: "Increased brand visibility by 200% on social media during the event." },
  { id: 5, title: "Skyline Developers", client: "Cityscape 2024", service: "Exhibitions", industry: "Real Estate", scale: "Large", year: 2024, image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 300, location: "Dubai World Trade Centre", timeline: "Concept to Completion: 10 weeks", challenge: "Showcasing multiple large-scale architectural models in an immersive, elegant setting.", result: "Achieved record-breaking off-plan sales during the 3-day event." },
  { id: 6, title: "Chronos Luxury", client: "Dubai Watch Week 2023", service: "Exhibitions", industry: "Luxury", scale: "Boutique", year: 2023, image: "https://images.pexels.com/photos/2804327/pexels-photo-2804327.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 80, location: "DIFC", timeline: "Concept to Completion: 9 weeks", challenge: "Creating museum-grade lighting and security for high-value timepieces.", result: "Attracted top-tier collectors and media, featured in 3 international luxury magazines." },
  { id: 7, title: "Annual Leadership Summit", client: "Global Leaders Org", service: "Events", industry: "Corporate", scale: "Large", year: 2024, image: "https://images.pexels.com/photos/2422290/pexels-photo-2422290.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 1000, location: "Dubai World Trade Centre", timeline: "Full-service planning: 6 months", challenge: "Managing logistics for 500+ international delegates and 50 keynote speakers.", result: "Achieved a 98% attendee satisfaction rate." },
  { id: 8, title: "LuxAuto 'Spectre' Launch", client: "LuxAuto", service: "Events", industry: "Luxury", scale: "Standard", year: 2024, image: "https://images.pexels.com/photos/3764984/pexels-photo-3764984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 500, location: "Burj Park, Downtown Dubai", timeline: "Full-service planning: 4 months", challenge: "Executing a dramatic, high-impact vehicle reveal with live broadcast elements.", result: "Generated over 10 million social media impressions within 24 hours." },
  { id: 9, title: "Downtown Corporate HQ", client: "Emirates Tech Solutions", service: "Interior Design", industry: "Technology", scale: "Mega", year: 2023, image: "https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 1200, location: "Downtown Dubai", timeline: "Design & Build: 9 months", challenge: "Designing a futuristic workspace to foster collaboration and attract top talent.", result: "Employee retention improved by 25% post-relocation." },
  { id: 10, title: "Palm Jumeirah Villa", client: "Confidential Client", service: "Interior Design", industry: "Residential", scale: "Large", year: 2024, image: "https://images.pexels.com/photos/6284223/pexels-photo-6284223.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 800, location: "Palm Jumeirah, Dubai", timeline: "Design & Furnishing: 7 months", challenge: "Blending contemporary coastal luxury with the client's extensive art collection.", result: "Project value increased by 20% upon completion." },
  { id: 11, title: "Boutique Retail Flagship", client: "Haute Couture DXB", service: "Interior Design", industry: "Retail", scale: "Standard", year: 2023, image: "https://images.pexels.com/photos/5864190/pexels-photo-5864190.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 300, location: "Dubai Mall", timeline: "Design & Fit-out: 5 months", challenge: "Creating an iconic, Instagrammable retail experience in a high-traffic luxury mall.", result: "Footfall exceeded projections by 30% in the first quarter." },
  { id: 12, title: "Tech Startup Festival", client: "Innovate MENA", service: "Events", industry: "Technology", scale: "Mega", year: 2023, image: "https://images.pexels.com/photos/7821516/pexels-photo-7821516.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 2000, location: "Dubai Design District", timeline: "Full-service planning: 8 months", challenge: "Coordinating over 100 startup booths, 3 stages, and networking zones.", result: "Facilitated over $15M in seed funding for participating startups." },
  { id: 13, title: "Future Mobility Pavilion", client: "Dubai Motor Show 2023", service: "Exhibitions", industry: "Automotive", scale: "Mega", year: 2023, image: "https://images.pexels.com/photos/14297491/pexels-photo-14297491.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 800, location: "Dubai World Trade Centre", timeline: "Concept to Completion: 14 weeks", challenge: "Creating a multi-brand experience showcasing electric and autonomous vehicles with interactive driving simulators.", result: "Voted 'Best Pavilion' by event organizers and featured on major news outlets." },
  { id: 14, title: "Sustainable Futures Hub", client: "WETEX 2023", service: "Exhibitions", industry: "Energy", scale: "Large", year: 2023, image: "https://images.pexels.com/photos/416405/pexels-photo-416405.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 350, location: "Dubai World Trade Centre", timeline: "Concept to Completion: 9 weeks", challenge: "Constructing the stand using 80% recycled and sustainable materials without compromising on a premium finish.", result: "Set a new benchmark for eco-friendly stand design, winning a sustainability award." },
  { id: 15, title: "Galactic Gala Dinner", client: "Emirates Space Agency", service: "Events", industry: "Aviation", scale: "Standard", year: 2024, image: "https://images.pexels.com/photos/94843/pexels-photo-94843.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 600, location: "Armani Hotel, Burj Khalifa", timeline: "Full-service planning: 5 months", challenge: "Creating a 'Night among the stars' theme with projection mapping and immersive decor for international astronauts and dignitaries.", result: "Praised for its creativity and flawless execution, strengthening international partnerships." },
  { id: 16, title: "FinTech Innovators Forum", client: "MENA Finance Hub", service: "Events", industry: "Finance", scale: "Large", year: 2024, image: "https://images.pexels.com/photos/8431835/pexels-photo-8431835.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 1500, location: "Madinat Jumeirah Conference Centre", timeline: "Full-service planning: 7 months", challenge: "Designing a dynamic event with multiple breakout zones, a live broadcast studio, and seamless tech integration for 1000+ attendees.", result: "Trended #1 on LinkedIn in the UAE for two days, with a 95% positive feedback score." },
  { id: 17, title: "The Alchemist's Cafe", client: "Elixir Specialty Coffee", service: "Interior Design", industry: "Hospitality", scale: "Boutique", year: 2024, image: "https://images.pexels.com/photos/1307698/pexels-photo-1307698.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 150, location: "Alserkal Avenue, Dubai", timeline: "Design & Fit-out: 4 months", challenge: "Creating a unique, intimate atmosphere that reflects the art of coffee making in a compact, industrial space.", result: "Became a local hotspot, featured in Time Out Dubai as 'Most Instagrammable New Cafe'." },
  { id: 18, title: "Executive Sky Lounge", client: "DIFC Capital Ventures", service: "Interior Design", industry: "Corporate", scale: "Standard", year: 2023, image: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", sqm: 450, location: "DIFC", timeline: "Design & Build: 6 months", challenge: "Designing a multi-functional space for high-level meetings, client entertainment, and relaxation, with state-of-the-art technology.", result: "Significantly enhanced the firm's client hosting capabilities and corporate image." },
];

export const regionalEvents: Event[] = [
  // --- UAE 2024 ---
  { name: "Sleep Expo Middle East", date: "Sep 10-12, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Retail" },
  { name: "Sign and Graphic Imaging Middle East", date: "Sep 24-26, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Marketing" },
  { name: "The Hotel Show Dubai", date: "Sep 24-26, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Hospitality" },
  { name: "Watch & Jewellery Show Sharjah", date: "Oct 2-6, 2024", venue: "Expo Centre Sharjah", country: "UAE", industry: "Luxury" },
  { name: "Expand North Star", date: "Oct 13-16, 2024", venue: "Dubai Harbour", country: "UAE", industry: "Technology" },
  { name: "GITEX Global", date: "Oct 14-18, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Technology" },
  { name: "Fintech Surge", date: "Oct 14-18, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Finance" },
  { name: "Marketing Mania", date: "Oct 14-18, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Marketing" },
  { name: "World Blockchain Summit", date: "Oct 22-23, 2024", venue: "Atlantis, The Palm", country: "UAE", industry: "Finance" },
  { name: "NAJAH Abu Dhabi", date: "Oct 27-29, 2024", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Education" },
  { name: "Beautyworld Middle East", date: "Oct 28-30, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Beauty" },
  { name: "Sharjah International Book Fair", date: "Nov 1-12, 2024", venue: "Expo Centre Sharjah", country: "UAE", industry: "Culture" },
  { name: "Gulfood Manufacturing", date: "Nov 5-7, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "Downtown Design", date: "Nov 6-9, 2024", venue: "Dubai Design District (d3)", country: "UAE", industry: "Art & Design" },
  { name: "ADIPEC", date: "Nov 11-14, 2024", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Energy" },
  { name: "Cityscape Global", date: "Nov 19-21, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Real Estate" },
  { name: "Big 5 Global", date: "Nov 26-29, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Construction" },
  { name: "FM Expo", date: "Nov 26-29, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Real Estate" },
  { name: "Middle East Film & Comic Con", date: "Dec 6-8, 2024", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Entertainment" },
  { name: "MEBAA Show", date: "Dec 10-12, 2024", venue: "DWC, Dubai Airshow Site", country: "UAE", industry: "Aviation"},
  { name: "ArabPlast", date: "Dec 13-15, 2024", venue: "Dubai World Trade Centre", country: "UAE", industry: "Manufacturing" },

  // --- KSA 2024 ---
  { name: "Global AI Summit", date: "Sep 10-12, 2024", venue: "King Abdulaziz Conference Center, Riyadh", country: "KSA", industry: "Technology" },
  { name: "Hotel & Hospitality Expo Saudi Arabia", date: "Sep 10-12, 2024", venue: "Riyadh Front", country: "KSA", industry: "Hospitality" },
  { name: "INDEX Saudi", date: "Sep 10-12, 2024", venue: "Riyadh Front", country: "KSA", industry: "Interior Design" },
  { name: "Cityscape Global KSA", date: "Sep 10-13, 2024", venue: "Riyadh Exhibition and Convention Center", country: "KSA", industry: "Real Estate" },
  { name: "Saudi Food Expo", date: "Sep 17-19, 2024", venue: "Riyadh Front", country: "KSA", industry: "Food & Beverage" },
  { name: "Saudi Infrastructure Expo", date: "Sep 24-26, 2024", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Construction" },
  { name: "Riyadh International Book Fair", date: "Sep 26 - Oct 5, 2024", venue: "Riyadh Front", country: "KSA", industry: "Culture" },
  { name: "Saudi Agriculture", date: "Oct 21-24, 2024", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Food & Beverage" },
  { name: "Global Health Exhibition", date: "Oct 27-29, 2024", venue: "Riyadh Front", country: "KSA", industry: "Healthcare" },
  { name: "Saudi Build", date: "Nov 4-7, 2024", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Construction" },
  { name: "Misk Global Forum", date: "Nov 12-14, 2024", venue: "Riyadh", country: "KSA", industry: "Education" },
  { name: "Saudi Power", date: "Nov 25-27, 2024", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Energy" },
  { name: "Black Hat Middle East & Africa", date: "Nov 26-28, 2024", venue: "Riyadh Front", country: "KSA", industry: "Security" },
  { name: "Saudi International Motor Show", date: "Dec 5-8, 2024", venue: "Jeddah Superdome", country: "KSA", industry: "Automotive" },
  { name: "Jeddah International Trade Fair", date: "Dec 15-18, 2024", venue: "Jeddah Centre for Forums & Events", country: "KSA", industry: "Retail" },

  // --- UAE 2025 ---
  { name: "World Future Energy Summit", date: "Jan 13-15, 2025", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Energy" },
  { name: "Intersec", date: "Jan 14-16, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Security" },
  { name: "Light Middle East", date: "Jan 17-19, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Construction" },
  { name: "World of Coffee Dubai", date: "Jan 21-23, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "Arab Health", date: "Jan 27-30, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Healthcare" },
  { name: "AEEDC Dubai", date: "Feb 4-6, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Healthcare" },
  { name: "Breakbulk Middle East", date: "Feb 10-11, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Logistics" },
  { name: "STEP Conference", date: "Feb 11-12, 2025", venue: "Dubai Internet City", country: "UAE", industry: "Technology" },
  { name: "International Property Show", date: "Feb 12-14, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Real Estate" },
  { name: "IDEX & NAVDEX", date: "Feb 17-21, 2025", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Defence" },
  { name: "Gulfood", date: "Feb 17-21, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "Dubai Food Festival", date: "Feb 28 - Mar 15, 2025", venue: "City-wide, Dubai", country: "UAE", industry: "Food & Beverage"},
  { name: "Dubai Derma", date: "Mar 3-5, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Healthcare" },
  { name: "World Police Summit", date: "Mar 5-7, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Security" },
  { name: "Dubai International Boat Show", date: "Mar 5-9, 2025", venue: "Dubai Harbour", country: "UAE", industry: "Luxury" },
  { name: "Art Dubai", date: "Mar 12-15, 2025", venue: "Madinat Jumeirah", country: "UAE", industry: "Art & Design" },
  { name: "Dubai International Horse Fair", date: "Mar 21-23, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Equestrian" },
  { name: "Custom Show Emirates", date: "Mar 21-23, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Automotive" },
  { name: "GESS Dubai", date: "Mar 25-27, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Education" },
  { name: "World Art Dubai", date: "Apr 2-5, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Art & Design" },
  { name: "Middle East Energy", date: "Apr 15-17, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Energy" },
  { name: "Global AI Show", date: "Apr 16-17, 2025", venue: "Dubai Festival City", country: "UAE", industry: "Technology" },
  { name: "GISEC Global", date: "Apr 21-23, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Technology" },
  { name: "Middle East Rail", date: "Apr 22-23, 2025", venue: "ADNEC, Abu Dhabi", country: "UAE", industry: "Logistics" },
  { name: "Arabian Travel Market", date: "Apr 28 - May 1, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Hospitality" },
  { name: "CABSAT", date: "May 13-15, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Media" },
  { name: "Paperworld Middle East", date: "May 19-21, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Retail"},
  { name: "Airport Show", date: "May 20-22, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Aviation" },
  { name: "Automechanika Dubai", date: "May 27-29, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Automotive" },
  { name: "INDEX Dubai", date: "Jun 3-5, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Interior Design" },
  { name: "Seamless Middle East", date: "Sep 9-10, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Retail" },
  { name: "Seatrade Maritime Middle East", date: "Sep 16-18, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Logistics"},
  { name: "WETEX and Dubai Solar Show", date: "Sep 23-25, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Energy" },
  { name: "GITEX Global 2025", date: "Oct 13-17, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Technology" },
  { name: "Dubai Muscle Show & Dubai Active", date: "Oct 24-26, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Fitness" },
  { name: "Beautyworld Middle East 2025", date: "Oct 27-29, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Beauty" },
  { name: "Gulfood Manufacturing 2025", date: "Nov 4-6, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "Dubai Airshow", date: "Nov 17-21, 2025", venue: "DWC, Dubai Airshow Site", country: "UAE", industry: "Aviation" },
  { name: "Cityscape Global 2025", date: "Nov 18-20, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Real Estate" },
  { name: "Big 5 Global 2025", date: "Nov 25-28, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Construction" },
  { name: "Dubai International Jewellery Show", date: "Dec 2-5, 2025", venue: "Dubai World Trade Centre", country: "UAE", industry: "Luxury" },

  // --- KSA 2025 ---
  { name: "Saudi Plastics & Petrochem", date: "Jan 13-16, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Manufacturing" },
  { name: "Saudi Print & Pack", date: "Jan 27-30, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Manufacturing" },
  { name: "World Defense Show", date: "Feb 8-12, 2025", venue: "Riyadh", country: "KSA", industry: "Defence" },
  { name: "LEAP", date: "Feb 10-13, 2025", venue: "Riyadh Exhibition and Convention Center", country: "KSA", industry: "Technology" },
  { name: "The Big 5 Saudi", date: "Feb 24-27, 2025", venue: "Riyadh Front", country: "KSA", industry: "Construction" },
  { name: "Saudi Entertainment and Amusement (SEA) Expo", date: "May 20-22, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Entertainment" },
  { name: "Saudi Light & Sound Expo", date: "May 20-22, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Entertainment" },
  { name: "Saudi Elenex", date: "May 26-28, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Energy" },
  { name: "Saudi Health", date: "Oct 19-21, 2025", venue: "Riyadh International Convention & Exhibition Center", country: "KSA", industry: "Healthcare" },
  { name: "Foodex Saudi", date: "Oct 26-29, 2025", venue: "Jeddah Centre for Forums & Events", country: "KSA", industry: "Food & Beverage" },
  { name: "InFlavour", date: "Nov 11-13, 2025", venue: "Riyadh Front", country: "KSA", industry: "Food & Beverage" },
  
  // --- UAE 2026 (Projected Dates) ---
  { name: "Intersec 2026", date: "Jan 13-15, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Security" },
  { name: "Arab Health 2026", date: "Jan 26-29, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Healthcare" },
  { name: "Gulfood 2026", date: "Feb 16-20, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Food & Beverage" },
  { name: "GITEX Global 2026", date: "Oct 12-16, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Technology" },
  { name: "Big 5 Global 2026", date: "Nov 24-27, 2026 (TBC)", venue: "Dubai World Trade Centre", country: "UAE", industry: "Construction" },
  
  // --- KSA 2026 (Projected Dates) ---
  { name: "LEAP 2026", date: "Feb 9-12, 2026 (TBC)", venue: "Riyadh Exhibition and Convention Center", country: "KSA", industry: "Technology" },
  { name: "The Big 5 Saudi 2026", date: "Feb 23-26, 2026 (TBC)", venue: "Riyadh Front", country: "KSA", industry: "Construction" },
];

export const testimonials: Testimonial[] = [
  { quote: "FANN didn't just build a stand; they created an experience. Their attention to detail and project management is unparalleled. Our leads increased by 40%!", client: "Aisha Al Futtaim", company: "TechVision AI", projectType: "GITEX Exhibition" },
  { quote: "The team at FANN is a dream to work with. They took our vision for the annual gala and elevated it beyond our wildest expectations. Flawless execution from start to finish.", client: "Johnathan Lee", company: "Global Leaders Org", projectType: "Corporate Event" },
  { quote: "Transforming our new headquarters with FANN was the best decision we made. The design is not only beautiful but has tangibly improved our team's collaboration and morale.", client: "Fatima Al Mansouri", company: "Emirates Tech Solutions", projectType: "Interior Design" },
];

export const pricingPlans = [
  {
    name: "Free",
    price: "0 AED",
    description: "Test the platform and get a feel for our design capabilities.",
    features: [
      "2 Generations Total (8 Images)",
      "Watermarked Previews",
      "Standard Resolution",
      "All Design Categories",
      "7-Day Design Storage",
    ],
    cta: "Start Designing",
    isPopular: false,
    ctaLink: '/fann-studio',
  },
  {
    name: "One-Time Package",
    price: "150 AED",
    priceDetails: "one-time payment",
    description: "Perfect for a single project without any subscription commitment.",
    features: [
      "10 Generations (40 Images)",
      "No Watermarks",
      "High-Resolution Exports (4K)",
      "PNG, JPG & PDF Exports",
      "Valid for 30 Days",
      "24-hour Email Support",
    ],
    cta: "Buy Now",
    isPopular: false,
    ctaLink: '/contact',
  },
  {
    name: "Starter",
    price: "299 AED",
    priceDetails: "per month",
    description: "Ideal for freelancers and small agencies with ongoing projects.",
    features: [
      "50 Generations / month",
      "Unused Generations Rollover (up to 20)",
      "Everything in One-Time, plus:",
      "Premium Template Library",
      "Permanent Design Storage",
      "Team Collaboration (3 Viewers)",
      "12-hour Priority Support",
    ],
    cta: "Choose Plan",
    isPopular: true,
    ctaLink: '/contact',
  },
  {
    name: "Professional",
    price: "599 AED",
    priceDetails: "per month",
    description: "Unlimited creativity for professional designers and large agencies.",
    features: [
      "Unlimited Generations",
      "Everything in Starter, plus:",
      "Pro Quality Rendering",
      "CAD & 3D Model Exports",
      "White-Label Options",
      "Phone & WhatsApp Support",
      "API Access",
      "Team Collaboration (10 Members)",
    ],
    cta: "Get Started",
    isPopular: false,
    ctaLink: '/contact',
  },
    {
    name: "Enterprise",
    price: "Custom",
    priceDetails: "starting at 2,500 AED/mo",
    description: "A complete turnkey solution: from AI concept to on-site reality.",
    features: [
      "Everything in Professional, plus:",
      "Full-Service Design Consultation",
      "**Fabrication & Installation**",
      "Dedicated Project Manager",
      "Custom AI Model Training",
      "24/7 Priority Support & SLA",
      "On-site Event Support",
    ],
    cta: "Contact Sales",
    isPopular: false,
    ctaLink: '/contact',
  },
];


export const countryCodes = [
    { "name": "United Arab Emirates", "dial_code": "+971", "code": "AE" }, { "name": "Saudi Arabia", "dial_code": "+966", "code": "SA" }, { "name": "Qatar", "dial_code": "+974", "code": "QA" }, { "name": "Oman", "dial_code": "+968", "code": "OM" }, { "name": "Kuwait", "dial_code": "+965", "code": "KW" }, { "name": "Bahrain", "dial_code": "+973", "code": "BH" }, { "name": "Egypt", "dial_code": "+20", "code": "EG" }, { "name": "Jordan", "dial_code": "+962", "code": "JO" }, { "name": "Lebanon", "dial_code": "+961", "code": "LB" }, { "name": "United States", "dial_code": "+1", "code": "US" }, { "name": "United Kingdom", "dial_code": "+44", "code": "GB" }, { "name": "India", "dial_code": "+91", "code": "IN" }, { "name": "Pakistan", "dial_code": "+92", "code": "PK" }, { "name": "Afghanistan", "dial_code": "+93", "code": "AF" }, { "name": "Albania", "dial_code": "+355", "code": "AL" }, { "name": "Algeria", "dial_code": "+213", "code": "DZ" }, { "name": "American Samoa", "dial_code": "+1684", "code": "AS" }, { "name": "Andorra", "dial_code": "+376", "code": "AD" }, { "name": "Angola", "dial_code": "+244", "code": "AO" }, { "name": "Anguilla", "dial_code": "+1264", "code": "AI" }, { "name": "Antarctica", "dial_code": "+672", "code": "AQ" }, { "name": "Antigua and Barbuda", "dial_code": "+1268", "code": "AG" }, { "name": "Argentina", "dial_code": "+54", "code": "AR" }, { "name": "Armenia", "dial_code": "+374", "code": "AM" }, { "name": "Aruba", "dial_code": "+297", "code": "AW" }, { "name": "Australia", "dial_code": "+61", "code": "AU" }, { "name": "Austria", "dial_code": "+43", "code": "AT" }, { "name": "Azerbaijan", "dial_code": "+994", "code": "AZ" }, { "name": "Bahamas", "dial_code": "+1242", "code": "BS" }, { "name": "Bangladesh", "dial_code": "+880", "code": "BD" }, { "name": "Barbados", "dial_code": "+1246", "code": "BB" }, { "name": "Belarus", "dial_code": "+375", "code": "BY" }, { "name": "Belgium", "dial_code": "+32", "code": "BE" }, { "name": "Belize", "dial_code": "+501", "code": "BZ" }, { "name": "Benin", "dial_code": "+229", "code": "BJ" }, { "name": "Bermuda", "dial_code": "+1441", "code": "BM" }, { "name": "Bhutan", "dial_code": "+975", "code": "BT" }, { "name": "Bolivia, Plurinational State of", "dial_code": "+591", "code": "BO" }, { "name": "Bosnia and Herzegovina", "dial_code": "+387", "code": "BA" }, { "name": "Botswana", "dial_code": "+267", "code": "BW" }, { "name": "Brazil", "dial_code": "+55", "code": "BR" }, { "name": "British Indian Ocean Territory", "dial_code": "+246", "code": "IO" }, { "name": "Brunei Darussalam", "dial_code": "+673", "code": "BN" }, { "name": "Bulgaria", "dial_code": "+359", "code": "BG" }, { "name": "Burkina Faso", "dial_code": "+226", "code": "BF" }, { "name": "Burundi", "dial_code": "+257", "code": "BI" }, { "name": "Cambodia", "dial_code": "+855", "code": "KH" }, { "name": "Cameroon", "dial_code": "+237", "code": "CM" }, { "name": "Canada", "dial_code": "+1", "code": "CA" }, { "name": "Cape Verde", "dial_code": "+238", "code": "CV" }, { "name": "Cayman Islands", "dial_code": "+345", "code": "KY" }, { "name": "Central African Republic", "dial_code": "+236", "code": "CF" }, { "name": "Chad", "dial_code": "+235", "code": "TD" }, { "name": "Chile", "dial_code": "+56", "code": "CL" }, { "name": "China", "dial_code": "+86", "code": "CN" }, { "name": "Christmas Island", "dial_code": "+61", "code": "CX" }, { "name": "Cocos (Keeling) Islands", "dial_code": "+61", "code": "CC" }, { "name": "Colombia", "dial_code": "+57", "code": "CO" }, { "name": "Comoros", "dial_code": "+269", "code": "KM" }, { "name": "Congo", "dial_code": "+242", "code": "CG" }, { "name": "Congo, The Democratic Republic of the", "dial_code": "+243", "code": "CD" }, { "name": "Cook Islands", "dial_code": "+682", "code": "CK" }, { "name": "Costa Rica", "dial_code": "+506", "code": "CR" }, { "name": "Cote d'Ivoire", "dial_code": "+225", "code": "CI" }, { "name": "Croatia", "dial_code": "+385", "code": "HR" }, { "name": "Cuba", "dial_code": "+53", "code": "CU" }, { "name": "Cyprus", "dial_code": "+357", "code": "CY" }, { "name": "Czech Republic", "dial_code": "+420", "code": "CZ" }, { "name": "Denmark", "dial_code": "+45", "code": "DK" }, { "name": "Djibouti", "dial_code": "+253", "code": "DJ" }, { "name": "Dominica", "dial_code": "+1767", "code": "DM" }, { "name": "Dominican Republic", "dial_code": "+1849", "code": "DO" }, { "name": "Ecuador", "dial_code": "+593", "code": "EC" }, { "name": "El Salvador", "dial_code": "+503", "code": "SV" }, { "name": "Equatorial Guinea", "dial_code": "+240", "code": "GQ" }, { "name": "Eritrea", "dial_code": "+291", "code": "ER" }, { "name": "Estonia", "dial_code": "+372", "code": "EE" }, { "name": "Ethiopia", "dial_code": "+251", "code": "ET" }, { "name": "Falkland Islands (Malvinas)", "dial_code": "+500", "code": "FK" }, { "name": "Faroe Islands", "dial_code": "+298", "code": "FO" }, { "name": "Fiji", "dial_code": "+679", "code": "FJ" }, { "name": "Finland", "dial_code": "+358", "code": "FI" }, { "name": "France", "dial_code": "+33", "code": "FR" }, { "name": "French Guiana", "dial_code": "+594", "code": "GF" }, { "name": "French Polynesia", "dial_code": "+689", "code": "PF" }, { "name": "Gabon", "dial_code": "+241", "code": "GA" }, { "name": "Gambia", "dial_code": "+220", "code": "GM" }, { "name": "Georgia", "dial_code": "+995", "code": "GE" }, { "name": "Germany", "dial_code": "+49", "code": "DE" }, { "name": "Ghana", "dial_code": "+233", "code": "GH" }, { "name": "Gibraltar", "dial_code": "+350", "code": "GI" }, { "name": "Greece", "dial_code": "+30", "code": "GR" }, { "name": "Greenland", "dial_code": "+299", "code": "GL" }, { "name": "Grenada", "dial_code": "+1473", "code": "GD" }, { "name": "Guadeloupe", "dial_code": "+590", "code": "GP" }, { "name": "Guam", "dial_code": "+1671", "code": "GU" }, { "name": "Guatemala", "dial_code": "+502", "code": "GT" }, { "name": "Guernsey", "dial_code": "+44", "code": "GG" }, { "name": "Guinea", "dial_code": "+224", "code": "GN" }, { "name": "Guinea-Bissau", "dial_code": "+245", "code": "GW" }, { "name": "Guyana", "dial_code": "+592", "code": "GY" }, { "name": "Haiti", "dial_code": "+509", "code": "HT" }, { "name": "Holy See (Vatican City State)", "dial_code": "+379", "code": "VA" }, { "name": "Honduras", "dial_code": "+504", "code": "HN" }, { "name": "Hong Kong", "dial_code": "+852", "code": "HK" }, { "name": "Hungary", "dial_code": "+36", "code": "HU" }, { "name": "Iceland", "dial_code": "+354", "code": "IS" }, { "name": "Indonesia", "dial_code": "+62", "code": "ID" }, { "name": "Iran, Islamic Republic of", "dial_code": "+98", "code": "IR" }, { "name": "Iraq", "dial_code": "+964", "code": "IQ" }, { "name": "Ireland", "dial_code": "+353", "code": "IE" }, { "name": "Isle of Man", "dial_code": "+44", "code": "IM" }, { "name": "Israel", "dial_code": "+972", "code": "IL" }, { "name": "Italy", "dial_code": "+39", "code": "IT" }, { "name": "Jamaica", "dial_code": "+1876", "code": "JM" }, { "name": "Japan", "dial_code": "+81", "code": "JP" }, { "name": "Jersey", "dial_code": "+44", "code": "JE" }, { "name": "Kazakhstan", "dial_code": "+7", "code": "KZ" }, { "name": "Kenya", "dial_code": "+254", "code": "KE" }, { "name": "Kiribati", "dial_code": "+686", "code": "KI" }, { "name": "Korea, Republic of", "dial_code": "+82", "code": "KR" }, { "name": "Kosovo", "dial_code": "+383", "code": "XK" }, { "name": "Kyrgyzstan", "dial_code": "+996", "code": "KG" }, { "name": "Lao People's Democratic Republic", "dial_code": "+856", "code": "LA" }, { "name": "Latvia", "dial_code": "+371", "code": "LV" }, { "name": "Lesotho", "dial_code": "+266", "code": "LS" }, { "name": "Liberia", "dial_code": "+231", "code": "LR" }, { "name": "Libyan Arab Jamahiriya", "dial_code": "+218", "code": "LY" }, { "name": "Liechtenstein", "dial_code": "+423", "code": "LI" }, { "name": "Lithuania", "dial_code": "+370", "code": "LT" }, { "name": "Luxembourg", "dial_code": "+352", "code": "LU" }, { "name": "Macao", "dial_code": "+853", "code": "MO" }, { "name": "Macedonia, The Former Yugoslav Republic of", "dial_code": "+389", "code": "MK" }, { "name": "Madagascar", "dial_code": "+261", "code": "MG" }, { "name": "Malawi", "dial_code": "+265", "code": "MW" }, { "name": "Malaysia", "dial_code": "+60", "code": "MY" }, { "name": "Maldives", "dial_code": "+960", "code": "MV" }, { "name": "Mali", "dial_code": "+223", "code": "ML" }, { "name": "Malta", "dial_code": "+356", "code": "MT" }, { "name": "Marshall Islands", "dial_code": "+692", "code": "MH" }, { "name": "Martinique", "dial_code": "+596", "code": "MQ" }, { "name": "Mauritania", "dial_code": "+222", "code": "MR" }, { "name": "Mauritius", "dial_code": "+230", "code": "MU" }, { "name": "Mayotte", "dial_code": "+262", "code": "YT" }, { "name": "Mexico", "dial_code": "+52", "code": "MX" }, { "name": "Micronesia, Federated States of", "dial_code": "+691", "code": "FM" }, { "name": "Moldova, Republic of", "dial_code": "+373", "code": "MD" }, { "name": "Monaco", "dial_code": "+377", "code": "MC" }, { "name": "Mongolia", "dial_code": "+976", "code": "MN" }, { "name": "Montenegro", "dial_code": "+382", "code": "ME" }, { "name": "Montserrat", "dial_code": "+1664", "code": "MS" }, { "name": "Morocco", "dial_code": "+212", "code": "MA" }, { "name": "Mozambique", "dial_code": "+258", "code": "MZ" }, { "name": "Myanmar", "dial_code": "+95", "code": "MM" }, { "name": "Namibia", "dial_code": "+264", "code": "NA" }, { "name": "Nauru", "dial_code": "+674", "code": "NR" }, { "name": "Nepal", "dial_code": "+977", "code": "NP" }, { "name": "Netherlands", "dial_code": "+31", "code": "NL" }, { "name": "New Caledonia", "dial_code": "+687", "code": "NC" }, { "name": "New Zealand", "dial_code": "+64", "code": "NZ" }, { "name": "Nicaragua", "dial_code": "+505", "code": "NI" }, { "name": "Niger", "dial_code": "+227", "code": "NE" }, { "name": "Nigeria", "dial_code": "+234", "code": "NG" }, { "name": "Niue", "dial_code": "+683", "code": "NU" }, { "name": "Norfolk Island", "dial_code": "+672", "code": "NF" }, { "name": "Northern Mariana Islands", "dial_code": "+1670", "code": "MP" }, { "name": "Norway", "dial_code": "+47", "code": "NO" }, { "name": "Palau", "dial_code": "+680", "code": "PW" }, { "name": "Palestinian Territory, Occupied", "dial_code": "+970", "code": "PS" }, { "name": "Panama", "dial_code": "+507", "code": "PA" }, { "name": "Papua New Guinea", "dial_code": "+675", "code": "PG" }, { "name": "Paraguay", "dial_code": "+595", "code": "PY" }, { "name": "Peru", "dial_code": "+51", "code": "PE" }, { "name": "Philippines", "dial_code": "+63", "code": "PH" }, { "name": "Pitcairn", "dial_code": "+872", "code": "PN" }, { "name": "Poland", "dial_code": "+48", "code": "PL" }, { "name": "Portugal", "dial_code": "+351", "code": "PT" }, { "name": "Puerto Rico", "dial_code": "+1939", "code": "PR" }, { "name": "Réunion", "dial_code": "+262", "code": "RE" }, { "name": "Romania", "dial_code": "+40", "code": "RO" }, { "name": "Russia", "dial_code": "+7", "code": "RU" }, { "name": "Rwanda", "dial_code": "+250", "code": "RW" }, { "name": "Saint Barthélemy", "dial_code": "+590", "code": "BL" }, { "name": "Saint Helena, Ascension and Tristan da Cunha", "dial_code": "+290", "code": "SH" }, { "name": "Saint Kitts and Nevis", "dial_code": "+1869", "code": "KN" }, { "name": "Saint Lucia", "dial_code": "+1758", "code": "LC" }, { "name": "Saint Martin", "dial_code": "+590", "code": "MF" }, { "name": "Saint Pierre and Miquelon", "dial_code": "+508", "code": "PM" }, { "name": "Saint Vincent and the Grenadines", "dial_code": "+1784", "code": "VC" }, { "name": "Samoa", "dial_code": "+685", "code": "WS" }, { "name": "San Marino", "dial_code": "+378", "code": "SM" }, { "name": "Sao Tome and Principe", "dial_code": "+239", "code": "ST" }, { "name": "Senegal", "dial_code": "+221", "code": "SN" }, { "name": "Serbia", "dial_code": "+381", "code": "RS" }, { "name": "Seychelles", "dial_code": "+248", "code": "SC" }, { "name": "Sierra Leone", "dial_code": "+232", "code": "SL" }, { "name": "Singapore", "dial_code": "+65", "code": "SG" }, { "name": "Slovakia", "dial_code": "+421", "code": "SK" }, { "name": "Slovenia", "dial_code": "+386", "code": "SI" }, { "name": "Solomon Islands", "dial_code": "+677", "code": "SB" }, { "name": "Somalia", "dial_code": "+252", "code": "SO" }, { "name": "South Africa", "dial_code": "+27", "code": "ZA" }, { "name": "Spain", "dial_code": "+34", "code": "ES" }, { "name": "Sri Lanka", "dial_code": "+94", "code": "LK" }, { "name": "Sudan", "dial_code": "+249", "code": "SD" }, { "name": "Suriname", "dial_code": "+597", "code": "SR" }, { "name": "Svalbard and Jan Mayen", "dial_code": "+47", "code": "SJ" }, { "name": "Swaziland", "dial_code": "+268", "code": "SZ" }, { "name": "Sweden", "dial_code": "+46", "code": "SE" }, { "name": "Switzerland", "dial_code": "+41", "code": "CH" }, { "name": "Syrian Arab Republic", "dial_code": "+963", "code": "SY" }, { "name": "Taiwan, Province of China", "dial_code": "+886", "code": "TW" }, { "name": "Tajikistan", "dial_code": "+992", "code": "TJ" }, { "name": "Tanzania, United Republic of", "dial_code": "+255", "code": "TZ" }, { "name": "Thailand", "dial_code": "+66", "code": "TH" }, { "name": "Timor-Leste", "dial_code": "+670", "code": "TL" }, { "name": "Togo", "dial_code": "+228", "code": "TG" }, { "name": "Tokelau", "dial_code": "+690", "code": "TK" }, { "name": "Tonga", "dial_code": "+676", "code": "TO" }, { "name": "Trinidad and Tobago", "dial_code": "+1868", "code": "TT" }, { "name": "Tunisia", "dial_code": "+216", "code": "TN" }, { "name": "Turkey", "dial_code": "+90", "code": "TR" }, { "name": "Turkmenistan", "dial_code": "+993", "code": "TM" }, { "name": "Turks and Caicos Islands", "dial_code": "+1649", "code": "TC" }, { "name": "Tuvalu", "dial_code": "+688", "code": "TV" }, { "name": "Uganda", "dial_code": "+256", "code": "UG" }, { "name": "Ukraine", "dial_code": "+380", "code": "UA" }, { "name": "Uruguay", "dial_code": "+598", "code": "UY" }, { "name": "Uzbekistan", "dial_code": "+998", "code": "UZ" }, { "name": "Vanuatu", "dial_code": "+678", "code": "VU" }, { "name": "Venezuela, Bolivarian Republic of", "dial_code": "+58", "code": "VE" }, { "name": "Viet Nam", "dial_code": "+84", "code": "VN" }, { "name": "Virgin Islands, British", "dial_code": "+1284", "code": "VG" }, { "name": "Virgin Islands, U.S.", "dial_code": "+1340", "code": "VI" }, { "name": "Wallis and Futuna", "dial_code": "+681", "code": "WF" }, { "name": "Yemen", "dial_code": "+967", "code": "YE" }, { "name": "Zambia", "dial_code": "+260", "code": "ZM" }, { "name": "Zimbabwe", "dial_code": "+263", "code": "ZW" }
];