name: Full SEO, Performance & Intelligence Automation
on:
  schedule:
    - cron: "0 3 * * 1"     # Weekly run (Monday 03:00 UTC)
  workflow_dispatch:

jobs:
  seo_performance_agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lighthouse & Dependencies
        run: |
          npm install -g lighthouse puppeteer
          mkdir -p reports

      - name: Run Lighthouse Audit
        run: |
          lighthouse https://aistudio.google.com/apps/drive/1K0LyVrxaxSV2r2FZlQY8ZAE1_3m6DcTs?showAssistant=true \
            --output=json \
            --output-path=reports/lighthouse-report.json \
            --chrome-flags="--headless"

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: reports/lighthouse-report.json

      - name: SEO & Content Intelligence
        uses: openai/assistant-action@v1
        with:
          model: gpt-5
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          google_search_console_token: ${{ secrets.GSC_TOKEN }}
          google_analytics_token: ${{ secrets.GA4_TOKEN }}
          serp_api_key: ${{ secrets.SERP_API_KEY }}
          prompt: |
            You are an autonomous SEO & Performance Optimization Agent managing the **FANN website**.

            **Targets**
            - Website: https://aistudio.google.com/apps/drive/1K0LyVrxaxSV2r2FZlQY8ZAE1_3m6DcTs?showAssistant=true
            - Deployment: https://vercel.com/eslammelsayedd-5685s-projects
            - Codebase: https://github.com/eslammelsayedd-pixel/fann-new-website-

            ## OBJECTIVES

            1. **Technical SEO**
               - Crawl all pages for meta/title/alt/robots/schema/sitemap/canonical/accessibility.
               - Auto-generate and commit missing assets.
               - Validate structured data via schema.org & Rich Results Test.
               - Save log → `/reports/seo-log.json`.

            2. **Performance & Core Web Vitals**
               - Parse `reports/lighthouse-report.json`.
               - Implement fixes (lazy-load, cache headers, image compression).
               - Re-deploy to Vercel and confirm performance recovery.

            3. **Content Optimization**
               - Analyze keyword coverage & semantic relevance.
               - Generate optimized text drafts → `/content-suggestions/`.
               - Maintain H1-H3 hierarchy and internal links.

            4. **Backlink Intelligence**
               - Query Search Console for referring domains.
               - Produce `/reports/disavow.txt` for toxic sources.
               - Recommend ethical backlink targets (AI / digital / web-dev / UAE niche).

            5. **Analytics & Keyword Tracking**
               - Pull GA4 metrics (sessions, bounce rate, avg engagement time, conversions).
               - Query SERP API for top 50 keywords, rank position, and competition.
               - Correlate organic traffic trends with keyword changes.
               - Output summary → `/reports/traffic-insights.json`.

            6. **Continuous Improvement**
               - Run weekly audits; open PR labelled `auto-fix` if metrics drop > 5%.
               - Aggregate results → `/reports/weekly-summary.md`.

            7. **Compliance & Ethics**
               - Follow Google Webmaster Guidelines.
               - Never execute black-hat or paid-link tactics.
               - Create GitHub issues for tasks needing human approval.

            ## OUTPUT
            - Updated SEO files
            - `reports/lighthouse-report.json`
            - `reports/seo-log.json`
            - `reports/traffic-insights.json`
            - `reports/weekly-summary.md`
            - `/content-suggestions/` with draft content

      - name: Upload SEO Reports
        uses: actions/upload-artifact@v4
        with:
          name: seo-performance-reports
          path: reports/

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "✅ FANN SEO & Performance Automation complete. Reports available in GitHub Actions artifacts."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
